### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by anttikup** [baldez300/Task-Management-Web-App#1]
### Application Overview Understanding
Users can reqister, login, logout and add and remove their tasks.

Code is clear and easy to read, but some function are a bit long and do many things.

### Code Structure and Quality

https://github.com/baldez300/Task-Management-Web-App/blob/48d40ff285917a392ba0b7b663ee00bfe576f92d/app/routes.py#L15-L33
Routes and business logic should be separated.

https://github.com/baldez300/Task-Management-Web-App/blob/48d40ff285917a392ba0b7b663ee00bfe576f92d/app/routes.py#L36-L53
Same. This could be clearer if the logging in was left at the bottom of the function, with all the exceptional cases returning early.

### Commit Analysis
There is only one commit. There is some placeholder code for the tasks which should have been another commit from the reqister/login/logout code at least. 

### Communication and Documentation
Documentation is good, and I managed to get the code running. 
Some issues:
- There were some packages missing in requirements.txt
- It was not clear that you should go to /register first
- An error here
https://github.com/baldez300/Task-Management-Web-App/blob/48d40ff285917a392ba0b7b663ee00bfe576f92d/README.md?plain=1#L77
(should be `'appuser@'localhost'`)

### Suggestions for Improvement
Task related code could be worked on in another branch until it is in working state.

**Comment by baldez300** [comment]
Thanks for the good review.!
