### ISSUE TITLE
[Arttu] Week 3 code review

### ISSUE THREAD

**Issue by pennane** [baldez300/Task-Management-Web-App#2]
**Application Overview Understanding**
- Task management app.

**Code Structure and Quality**
- Could make sense to move python code inside a `src` folder. This way the unavoidable noise of the repository root files becomes easier to handle.
- It could also make sense to extract db and models into its own directory
- But overall the current structure is logical and solid imo

**Commit Analysis**
Nice to have the additional description for the commit. Implemented features are clear. In the future prefer smaller and atomic commits

**Communication and Documentation**
- Good good. The migrations might not be straightforward for someone who does not know what they are. Could make sense to mention what they are and how they work in the readme for example

**Suggestions for Improvement**
- There are quite a few steps to setup the development environment. Could be cool to automate it with scripts / docker or whatever. Improves DX quite a bit if the setup feels like plug and play. 

**Other notes**
- The way migrations are handled is cool. Big up! Feels nice to read code that has smart stuff in it.

**Comment by baldez300** [comment]
Thanks for the good review.
