### ISSUE TITLE
review

### ISSUE THREAD

**Issue by elenabli** [baldez300/Task-Management-Web-App#3]
#### Application Overview Understanding:

The application appears to be a Flask-based web application with user authentication and task management features.

#### Code Structure and Quality:
The code is well-organized. The separation of routes, models, and initialization logic into distinct files enhances readability. 

#### Readability Without Effort:
Some of the blocks are too complicated to understand, I think they could be split up, especially the routing part.

#### Clear and Descriptive Naming:
Variable and function names are clear and descriptive, contributing to the overall readability. For instance, the Task and User models in app/models.py are appropriately named, providing a clear understanding of their roles.

#### Handling Negative Cases and Return Early:
I didn't notice any error handling, it would be nice to add them

#### Abstraction and Subcomponent Separation:
The code demonstrates the logical abstraction, especially in the separation of routes, models, and initialization logic. 

#### Atomic Commits and Informative Messages:
There's only one commit here, it's probably not a good practice. It would be better to divide commits into smaller commits. I know, I have the same problem...

#### Communication and Documentation:
Maybe it would be better to add more explanations or write them in the Readme.md

**Comment by baldez300** [comment]
Thanks for the good review.
